In [1]:
# program 1 mentioned in jupyter installaion guide link available on Assignment Link 

First lets's discuss some useful array attributes. We'll start by defining three random arrays, a one dimensional,two-dimensional and a three-dimensional array.
We'll use the numpy 's random number generator,which we will seed with a set value in order to ensure that same random arrays are generated each time this codes run.

In [63]:
import numpy as np


In [64]:
np.random.seed(0)
x1=np.random.randint(10 ,size=6)# one dimensional
x2=np.random.randint(10, size=(3,4))#two dimensional
x3=np.random.randint(10, size=(3,4,5))#three dimensional


In [65]:
print(x1)

[5 0 3 3 7 9]


In [66]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [67]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
